/*
* Generated file
*
* Generated from: yang module name: snbi-provider yang module local name: snbi-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jul 21 17:20:01 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.snbi.config.yang.config.snbi.provider.impl;
public class SnbiProviderModuleFactory extends org.opendaylight.snbi.config.yang.config.snbi.provider.impl.AbstractSnbiProviderModuleFactory {

}
