/*
 * Copyright (c) 2014, 2015 Cisco Systems, Inc. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: snbi-provider yang module local name: snbi-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jul 21 17:20:01 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.snbi.config.yang.config.snbi.provider.impl;
public class SnbiProviderModuleFactory extends org.opendaylight.snbi.config.yang.config.snbi.provider.impl.AbstractSnbiProviderModuleFactory {

}
