/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_clear_screen (cparser_t *parser)
{
    cparser_cmd_clear_screen(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_autonomic_interface (cparser_t *parser)
{
    cparser_cmd_show_autonomic_interface(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_ip_interfaces (cparser_t *parser)
{
    cparser_cmd_show_ip_interfaces(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_process (cparser_t *parser)
{
    cparser_cmd_show_process(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_device (cparser_t *parser)
{
    cparser_cmd_show_snbi_device(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_neighbors (cparser_t *parser)
{
    cparser_cmd_show_snbi_neighbors(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_intf_db (cparser_t *parser)
{
    cparser_cmd_show_snbi_intf_db(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_enable_privileged_mode (cparser_t *parser)
{
    cparser_cmd_enable_privileged_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_disable_privileged_mode (cparser_t *parser)
{
    cparser_cmd_disable_privileged_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi (cparser_t *parser)
{
    cparser_cmd_snbi(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_quit (cparser_t *parser)
{
    cparser_cmd_snbi_quit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_discovery (cparser_t *parser)
{
    cparser_cmd_snbi_discovery(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_no_discovery (cparser_t *parser)
{
    cparser_cmd_snbi_no_discovery(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_no_debug_neighbor_discovery_type_level (cparser_t *parser)
{
    char *type_val;
    char **type_ptr = NULL;
    char *level_val;
    char **level_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[3], &type_val);
    assert(CPARSER_OK == rc);
    type_ptr = &type_val;
    rc = cparser_get_list(&parser->tokens[4], &level_val);
    assert(CPARSER_OK == rc);
    level_ptr = &level_val;
    cparser_cmd_snbi_no_debug_neighbor_discovery_type_level(&parser->context,
        type_ptr,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_no_debug_bootstrap_type_level (cparser_t *parser)
{
    char *type_val;
    char **type_ptr = NULL;
    char *level_val;
    char **level_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[3], &type_val);
    assert(CPARSER_OK == rc);
    type_ptr = &type_val;
    rc = cparser_get_list(&parser->tokens[4], &level_val);
    assert(CPARSER_OK == rc);
    level_ptr = &level_val;
    cparser_cmd_snbi_no_debug_bootstrap_type_level(&parser->context,
        type_ptr,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_interface_start (cparser_t *parser)
{
    cparser_cmd_snbi_interface_start(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_interface_stop (cparser_t *parser)
{
    cparser_cmd_snbi_interface_stop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_start (cparser_t *parser)
{
    cparser_cmd_snbi_start(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_stop (cparser_t *parser)
{
    cparser_cmd_snbi_stop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_debug_log_console (cparser_t *parser)
{
    cparser_cmd_snbi_debug_log_console(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_debug_log_file_logfile (cparser_t *parser)
{
    char *logfile_val;
    char **logfile_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[3], &logfile_val);
    assert(CPARSER_OK == rc);
    logfile_ptr = &logfile_val;
    cparser_cmd_snbi_debug_log_file_logfile(&parser->context,
        logfile_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_debug_neighbor_discovery_type_level (cparser_t *parser)
{
    char *type_val;
    char **type_ptr = NULL;
    char *level_val;
    char **level_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[2], &type_val);
    assert(CPARSER_OK == rc);
    type_ptr = &type_val;
    rc = cparser_get_list(&parser->tokens[3], &level_val);
    assert(CPARSER_OK == rc);
    level_ptr = &level_val;
    cparser_cmd_snbi_debug_neighbor_discovery_type_level(&parser->context,
        type_ptr,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_debug_bootstrap_type_level (cparser_t *parser)
{
    char *type_val;
    char **type_ptr = NULL;
    char *level_val;
    char **level_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_list(&parser->tokens[2], &type_val);
    assert(CPARSER_OK == rc);
    type_ptr = &type_val;
    rc = cparser_get_list(&parser->tokens[3], &level_val);
    assert(CPARSER_OK == rc);
    level_ptr = &level_val;
    cparser_cmd_snbi_debug_bootstrap_type_level(&parser->context,
        type_ptr,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test (cparser_t *parser)
{
    cparser_cmd_test(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_get_firstnode (cparser_t *parser)
{
    cparser_cmd_test_avl_get_firstnode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_init (cparser_t *parser)
{
    cparser_cmd_test_avl_init(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_insert_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_insert_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_remove_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_remove_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_search_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_search_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_uninit (cparser_t *parser)
{
    cparser_cmd_test_avl_uninit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_walk (cparser_t *parser)
{
    cparser_cmd_test_avl_walk(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_create (cparser_t *parser)
{
    cparser_cmd_test_list_create(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_destroy (cparser_t *parser)
{
    cparser_cmd_test_list_destroy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_is_valid (cparser_t *parser)
{
    cparser_cmd_test_list_is_valid(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_is_empty (cparser_t *parser)
{
    cparser_cmd_test_list_is_empty(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_lookup_node_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_list_lookup_node_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_enqueue_node_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_list_enqueue_node_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_dequeue_node (cparser_t *parser)
{
    cparser_cmd_test_list_dequeue_node(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_remove_node_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_list_remove_node_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_get_head_data (cparser_t *parser)
{
    cparser_cmd_test_list_get_head_data(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_walk (cparser_t *parser)
{
    cparser_cmd_test_list_walk(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_list_iterator_walk (cparser_t *parser)
{
    cparser_cmd_test_list_iterator_walk(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_logging_stdout (cparser_t *parser)
{
    cparser_cmd_test_event_logging_stdout(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_pthread_create (cparser_t *parser)
{
    cparser_cmd_test_event_pthread_create(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_stop_evnt_loop (cparser_t *parser)
{
    cparser_cmd_test_event_stop_evnt_loop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_timer_create (cparser_t *parser)
{
    cparser_cmd_test_event_timer_create(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_timer_destroy (cparser_t *parser)
{
    cparser_cmd_test_event_timer_destroy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_timer_start_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_event_timer_start_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_timer_stop (cparser_t *parser)
{
    cparser_cmd_test_event_timer_stop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_timer_running (cparser_t *parser)
{
    cparser_cmd_test_event_timer_running(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_msg_q_create (cparser_t *parser)
{
    cparser_cmd_test_event_msg_q_create(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_msg_q_destroy (cparser_t *parser)
{
    cparser_cmd_test_event_msg_q_destroy(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_msg_q_enqueue_msgtype_valarg_ptrarg (cparser_t *parser)
{
    uint32_t msgtype_val;
    uint32_t *msgtype_ptr = NULL;
    uint32_t valarg_val;
    uint32_t *valarg_ptr = NULL;
    char *ptrarg_val;
    char **ptrarg_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &msgtype_val);
    assert(CPARSER_OK == rc);
    msgtype_ptr = &msgtype_val;
    rc = cparser_get_uint(&parser->tokens[3], &valarg_val);
    assert(CPARSER_OK == rc);
    valarg_ptr = &valarg_val;
    rc = cparser_get_string(&parser->tokens[4], &ptrarg_val);
    assert(CPARSER_OK == rc);
    ptrarg_ptr = &ptrarg_val;
    cparser_cmd_test_event_msg_q_enqueue_msgtype_valarg_ptrarg(&parser->context,
        msgtype_ptr,
        valarg_ptr,
        ptrarg_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_event_msg_q_scale (cparser_t *parser)
{
    cparser_cmd_test_event_msg_q_scale(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_create (cparser_t *parser)
{
    cparser_cmd_test_hash_create(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_destory (cparser_t *parser)
{
    cparser_cmd_test_hash_destory(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_insert_key_value (cparser_t *parser)
{
    char *key_val;
    char **key_ptr = NULL;
    char *value_val;
    char **value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &key_val);
    assert(CPARSER_OK == rc);
    key_ptr = &key_val;
    rc = cparser_get_string(&parser->tokens[3], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_hash_insert_key_value(&parser->context,
        key_ptr,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_lookup_key (cparser_t *parser)
{
    char *key_val;
    char **key_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &key_val);
    assert(CPARSER_OK == rc);
    key_ptr = &key_val;
    cparser_cmd_test_hash_lookup_key(&parser->context,
        key_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_remove_key (cparser_t *parser)
{
    char *key_val;
    char **key_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &key_val);
    assert(CPARSER_OK == rc);
    key_ptr = &key_val;
    cparser_cmd_test_hash_remove_key(&parser->context,
        key_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_hash_walk (cparser_t *parser)
{
    cparser_cmd_test_hash_walk(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_quit (cparser_t *parser)
{
    cparser_cmd_test_quit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_test_root_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_quit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    "Exit test submode",
    NULL,
    &cparser_node_test_root_quit_eol
};

cparser_node_t cparser_node_test_root_hash_walk_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_walk,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_walk = {
    CPARSER_NODE_KEYWORD,
    0,
    "walk",
    "Hash walk",
    NULL,
    &cparser_node_test_root_hash_walk_eol
};

cparser_node_t cparser_node_test_root_hash_remove_key_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_remove_key,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_remove_key = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:key>",
    "Key",
    NULL,
    &cparser_node_test_root_hash_remove_key_eol
};

cparser_node_t cparser_node_test_root_hash_remove = {
    CPARSER_NODE_KEYWORD,
    0,
    "remove",
    "Remove a value",
    &cparser_node_test_root_hash_walk,
    &cparser_node_test_root_hash_remove_key
};

cparser_node_t cparser_node_test_root_hash_lookup_key_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_lookup_key,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_lookup_key = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:key>",
    "Key",
    NULL,
    &cparser_node_test_root_hash_lookup_key_eol
};

cparser_node_t cparser_node_test_root_hash_lookup = {
    CPARSER_NODE_KEYWORD,
    0,
    "lookup",
    "Lookup a key",
    &cparser_node_test_root_hash_remove,
    &cparser_node_test_root_hash_lookup_key
};

cparser_node_t cparser_node_test_root_hash_insert_key_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_insert_key_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_insert_key_value = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:value>",
    "Value",
    NULL,
    &cparser_node_test_root_hash_insert_key_value_eol
};

cparser_node_t cparser_node_test_root_hash_insert_key = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:key>",
    "Key",
    NULL,
    &cparser_node_test_root_hash_insert_key_value
};

cparser_node_t cparser_node_test_root_hash_insert = {
    CPARSER_NODE_KEYWORD,
    0,
    "insert",
    "Insert a value",
    &cparser_node_test_root_hash_lookup,
    &cparser_node_test_root_hash_insert_key
};

cparser_node_t cparser_node_test_root_hash_destory_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_destory,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_destory = {
    CPARSER_NODE_KEYWORD,
    0,
    "destory",
    "Destroy hash",
    &cparser_node_test_root_hash_insert,
    &cparser_node_test_root_hash_destory_eol
};

cparser_node_t cparser_node_test_root_hash_create_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_hash_create,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_hash_create = {
    CPARSER_NODE_KEYWORD,
    0,
    "create",
    "Create hash",
    &cparser_node_test_root_hash_destory,
    &cparser_node_test_root_hash_create_eol
};

cparser_node_t cparser_node_test_root_hash = {
    CPARSER_NODE_KEYWORD,
    0,
    "hash",
    "Hash Test Command",
    &cparser_node_test_root_quit,
    &cparser_node_test_root_hash_create
};

cparser_node_t cparser_node_test_root_event_msg_q_scale_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_msg_q_scale,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_msg_q_scale = {
    CPARSER_NODE_KEYWORD,
    0,
    "msg-q-scale",
    "Scale test message queues",
    NULL,
    &cparser_node_test_root_event_msg_q_scale_eol
};

cparser_node_t cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg_ptrarg_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_msg_q_enqueue_msgtype_valarg_ptrarg,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg_ptrarg = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:ptrarg>",
    "Pointer argument",
    NULL,
    &cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg_ptrarg_eol
};

cparser_node_t cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:valarg>",
    "Value arguement",
    NULL,
    &cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg_ptrarg
};

cparser_node_t cparser_node_test_root_event_msg_q_enqueue_msgtype = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:msgtype>",
    "Message Type",
    NULL,
    &cparser_node_test_root_event_msg_q_enqueue_msgtype_valarg
};

cparser_node_t cparser_node_test_root_event_msg_q_enqueue = {
    CPARSER_NODE_KEYWORD,
    0,
    "msg-q-enqueue",
    "Enqueue a message",
    &cparser_node_test_root_event_msg_q_scale,
    &cparser_node_test_root_event_msg_q_enqueue_msgtype
};

cparser_node_t cparser_node_test_root_event_msg_q_destroy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_msg_q_destroy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_msg_q_destroy = {
    CPARSER_NODE_KEYWORD,
    0,
    "msg-q-destroy",
    "Destroy a Message Queue",
    &cparser_node_test_root_event_msg_q_enqueue,
    &cparser_node_test_root_event_msg_q_destroy_eol
};

cparser_node_t cparser_node_test_root_event_msg_q_create_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_msg_q_create,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_msg_q_create = {
    CPARSER_NODE_KEYWORD,
    0,
    "msg-q-create",
    "Create a Message queue",
    &cparser_node_test_root_event_msg_q_destroy,
    &cparser_node_test_root_event_msg_q_create_eol
};

cparser_node_t cparser_node_test_root_event_timer_running_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_timer_running,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_timer_running = {
    CPARSER_NODE_KEYWORD,
    0,
    "timer-running",
    "Check if the timer is running",
    &cparser_node_test_root_event_msg_q_create,
    &cparser_node_test_root_event_timer_running_eol
};

cparser_node_t cparser_node_test_root_event_timer_stop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_timer_stop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_timer_stop = {
    CPARSER_NODE_KEYWORD,
    0,
    "timer-stop",
    "Stop the Timer",
    &cparser_node_test_root_event_timer_running,
    &cparser_node_test_root_event_timer_stop_eol
};

cparser_node_t cparser_node_test_root_event_timer_start_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_timer_start_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_timer_start_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Seconds of expiry",
    NULL,
    &cparser_node_test_root_event_timer_start_value_eol
};

cparser_node_t cparser_node_test_root_event_timer_start = {
    CPARSER_NODE_KEYWORD,
    0,
    "timer-start",
    "Start the Timer",
    &cparser_node_test_root_event_timer_stop,
    &cparser_node_test_root_event_timer_start_value
};

cparser_node_t cparser_node_test_root_event_timer_destroy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_timer_destroy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_timer_destroy = {
    CPARSER_NODE_KEYWORD,
    0,
    "timer-destroy",
    "Destroy a Timer",
    &cparser_node_test_root_event_timer_start,
    &cparser_node_test_root_event_timer_destroy_eol
};

cparser_node_t cparser_node_test_root_event_timer_create_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_timer_create,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_timer_create = {
    CPARSER_NODE_KEYWORD,
    0,
    "timer-create",
    "Create a Timer",
    &cparser_node_test_root_event_timer_destroy,
    &cparser_node_test_root_event_timer_create_eol
};

cparser_node_t cparser_node_test_root_event_stop_evnt_loop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_stop_evnt_loop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_stop_evnt_loop = {
    CPARSER_NODE_KEYWORD,
    0,
    "stop-evnt-loop",
    "Stop the event loop",
    &cparser_node_test_root_event_timer_create,
    &cparser_node_test_root_event_stop_evnt_loop_eol
};

cparser_node_t cparser_node_test_root_event_pthread_create_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_pthread_create,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_pthread_create = {
    CPARSER_NODE_KEYWORD,
    0,
    "pthread-create",
    "Create a Pthread",
    &cparser_node_test_root_event_stop_evnt_loop,
    &cparser_node_test_root_event_pthread_create_eol
};

cparser_node_t cparser_node_test_root_event_logging_stdout_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_event_logging_stdout,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_event_logging_stdout = {
    CPARSER_NODE_KEYWORD,
    0,
    "logging-stdout",
    "Libevent logging",
    &cparser_node_test_root_event_pthread_create,
    &cparser_node_test_root_event_logging_stdout_eol
};

cparser_node_t cparser_node_test_root_event = {
    CPARSER_NODE_KEYWORD,
    0,
    "event",
    "Event Test Commands",
    &cparser_node_test_root_hash,
    &cparser_node_test_root_event_logging_stdout
};

cparser_node_t cparser_node_test_root_list_iterator_walk_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_iterator_walk,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_iterator_walk = {
    CPARSER_NODE_KEYWORD,
    0,
    "iterator-walk",
    "Walk using an iterator",
    NULL,
    &cparser_node_test_root_list_iterator_walk_eol
};

cparser_node_t cparser_node_test_root_list_walk_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_walk,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_walk = {
    CPARSER_NODE_KEYWORD,
    0,
    "walk",
    "List Walk",
    &cparser_node_test_root_list_iterator_walk,
    &cparser_node_test_root_list_walk_eol
};

cparser_node_t cparser_node_test_root_list_get_head_data_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_get_head_data,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_get_head_data = {
    CPARSER_NODE_KEYWORD,
    0,
    "get-head-data",
    "Get the data in the head of the list",
    &cparser_node_test_root_list_walk,
    &cparser_node_test_root_list_get_head_data_eol
};

cparser_node_t cparser_node_test_root_list_remove_node_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_remove_node_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_remove_node_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_list_remove_node_value_eol
};

cparser_node_t cparser_node_test_root_list_remove_node = {
    CPARSER_NODE_KEYWORD,
    0,
    "remove-node",
    "Remove a value from the list",
    &cparser_node_test_root_list_get_head_data,
    &cparser_node_test_root_list_remove_node_value
};

cparser_node_t cparser_node_test_root_list_dequeue_node_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_dequeue_node,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_dequeue_node = {
    CPARSER_NODE_KEYWORD,
    0,
    "dequeue-node",
    "Dequeue the value from the head of the list",
    &cparser_node_test_root_list_remove_node,
    &cparser_node_test_root_list_dequeue_node_eol
};

cparser_node_t cparser_node_test_root_list_enqueue_node_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_enqueue_node_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_enqueue_node_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_list_enqueue_node_value_eol
};

cparser_node_t cparser_node_test_root_list_enqueue_node = {
    CPARSER_NODE_KEYWORD,
    0,
    "enqueue-node",
    "Enqueue a value into the tail of the list",
    &cparser_node_test_root_list_dequeue_node,
    &cparser_node_test_root_list_enqueue_node_value
};

cparser_node_t cparser_node_test_root_list_lookup_node_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_lookup_node_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_lookup_node_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_list_lookup_node_value_eol
};

cparser_node_t cparser_node_test_root_list_lookup_node = {
    CPARSER_NODE_KEYWORD,
    0,
    "lookup-node",
    "Lookup a value exists in the list",
    &cparser_node_test_root_list_enqueue_node,
    &cparser_node_test_root_list_lookup_node_value
};

cparser_node_t cparser_node_test_root_list_is_empty_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_is_empty,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_is_empty = {
    CPARSER_NODE_KEYWORD,
    0,
    "is-empty",
    "Check if the list is empty",
    &cparser_node_test_root_list_lookup_node,
    &cparser_node_test_root_list_is_empty_eol
};

cparser_node_t cparser_node_test_root_list_is_valid_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_is_valid,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_is_valid = {
    CPARSER_NODE_KEYWORD,
    0,
    "is-valid",
    "Check the validity of the list",
    &cparser_node_test_root_list_is_empty,
    &cparser_node_test_root_list_is_valid_eol
};

cparser_node_t cparser_node_test_root_list_destroy_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_destroy,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_destroy = {
    CPARSER_NODE_KEYWORD,
    0,
    "destroy",
    "Destroy the list",
    &cparser_node_test_root_list_is_valid,
    &cparser_node_test_root_list_destroy_eol
};

cparser_node_t cparser_node_test_root_list_create_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_list_create,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_list_create = {
    CPARSER_NODE_KEYWORD,
    0,
    "create",
    "Create a List",
    &cparser_node_test_root_list_destroy,
    &cparser_node_test_root_list_create_eol
};

cparser_node_t cparser_node_test_root_list = {
    CPARSER_NODE_KEYWORD,
    0,
    "list",
    "List Test commands",
    &cparser_node_test_root_event,
    &cparser_node_test_root_list_create
};

cparser_node_t cparser_node_test_root_avl_walk_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_walk,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_walk = {
    CPARSER_NODE_KEYWORD,
    0,
    "walk",
    "Avl walk",
    NULL,
    &cparser_node_test_root_avl_walk_eol
};

cparser_node_t cparser_node_test_root_avl_uninit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_uninit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_uninit = {
    CPARSER_NODE_KEYWORD,
    0,
    "uninit",
    "Avl uninit",
    &cparser_node_test_root_avl_walk,
    &cparser_node_test_root_avl_uninit_eol
};

cparser_node_t cparser_node_test_root_avl_search_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_search_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_search_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_avl_search_value_eol
};

cparser_node_t cparser_node_test_root_avl_search = {
    CPARSER_NODE_KEYWORD,
    0,
    "search",
    "Avl search",
    &cparser_node_test_root_avl_uninit,
    &cparser_node_test_root_avl_search_value
};

cparser_node_t cparser_node_test_root_avl_remove_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_remove_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_remove_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_avl_remove_value_eol
};

cparser_node_t cparser_node_test_root_avl_remove = {
    CPARSER_NODE_KEYWORD,
    0,
    "remove",
    "Avl remove",
    &cparser_node_test_root_avl_search,
    &cparser_node_test_root_avl_remove_value
};

cparser_node_t cparser_node_test_root_avl_insert_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_insert_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_insert_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    "Integer value",
    NULL,
    &cparser_node_test_root_avl_insert_value_eol
};

cparser_node_t cparser_node_test_root_avl_insert = {
    CPARSER_NODE_KEYWORD,
    0,
    "insert",
    "Avl insert",
    &cparser_node_test_root_avl_remove,
    &cparser_node_test_root_avl_insert_value
};

cparser_node_t cparser_node_test_root_avl_init_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_init,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_init = {
    CPARSER_NODE_KEYWORD,
    0,
    "init",
    "Avl init",
    &cparser_node_test_root_avl_insert,
    &cparser_node_test_root_avl_init_eol
};

cparser_node_t cparser_node_test_root_avl_get_firstnode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_get_firstnode,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_root_avl_get_firstnode = {
    CPARSER_NODE_KEYWORD,
    0,
    "get-firstnode",
    "Get avl first node",
    &cparser_node_test_root_avl_init,
    &cparser_node_test_root_avl_get_firstnode_eol
};

cparser_node_t cparser_node_test_root_avl = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl",
    "Avl Test commands",
    &cparser_node_test_root_list,
    &cparser_node_test_root_avl_get_firstnode
};

cparser_node_t cparser_node_test_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode test",
    NULL,
    &cparser_node_test_root_avl
};

cparser_node_t cparser_node_test_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test,
    NULL,
    NULL,
    &cparser_node_test_root
};

cparser_node_t cparser_node_test = {
    CPARSER_NODE_KEYWORD,
    0,
    "test",
    "Test mode",
    NULL,
    &cparser_node_test_eol
};

cparser_node_t cparser_node_snbi_root_debug_bootstrap_type_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_debug_bootstrap_type_level,
    NULL,
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_level_sev = {
    NULL,
    "sev"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_level_moderate = {
    &cparser_list_node_snbi_root_debug_bootstrap_type_level_sev,
    "moderate"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_level_info = {
    &cparser_list_node_snbi_root_debug_bootstrap_type_level_moderate,
    "info"
 };

cparser_node_t cparser_node_snbi_root_debug_bootstrap_type_level = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_debug_bootstrap_type_level_info,
    "Debugging level",
    NULL,
    &cparser_node_snbi_root_debug_bootstrap_type_level_eol
};

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_packets = {
    NULL,
    "packets"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_events = {
    &cparser_list_node_snbi_root_debug_bootstrap_type_packets,
    "events"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_bootstrap_type_all = {
    &cparser_list_node_snbi_root_debug_bootstrap_type_events,
    "all"
 };

cparser_node_t cparser_node_snbi_root_debug_bootstrap_type = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_debug_bootstrap_type_all,
    "Type of debugging",
    NULL,
    &cparser_node_snbi_root_debug_bootstrap_type_level
};

cparser_node_t cparser_node_snbi_root_debug_bootstrap = {
    CPARSER_NODE_KEYWORD,
    0,
    "bootstrap",
    "Bootstrap debug information",
    NULL,
    &cparser_node_snbi_root_debug_bootstrap_type
};

cparser_node_t cparser_node_snbi_root_debug_neighbor_discovery_type_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_debug_neighbor_discovery_type_level,
    NULL,
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_sev = {
    NULL,
    "sev"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_moderate = {
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_sev,
    "moderate"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_info = {
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_moderate,
    "info"
 };

cparser_node_t cparser_node_snbi_root_debug_neighbor_discovery_type_level = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_level_info,
    "Debugging level",
    NULL,
    &cparser_node_snbi_root_debug_neighbor_discovery_type_level_eol
};

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_packets = {
    NULL,
    "packets"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_events = {
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_packets,
    "events"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_database = {
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_events,
    "database"
 };

cparser_list_node_t cparser_list_node_snbi_root_debug_neighbor_discovery_type_all = {
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_database,
    "all"
 };

cparser_node_t cparser_node_snbi_root_debug_neighbor_discovery_type = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_debug_neighbor_discovery_type_all,
    "Type of debugging",
    NULL,
    &cparser_node_snbi_root_debug_neighbor_discovery_type_level
};

cparser_node_t cparser_node_snbi_root_debug_neighbor_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "neighbor-discovery",
    "Neighbor discovery debug information",
    &cparser_node_snbi_root_debug_bootstrap,
    &cparser_node_snbi_root_debug_neighbor_discovery_type
};

cparser_node_t cparser_node_snbi_root_debug_log_file_logfile_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_debug_log_file_logfile,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_debug_log_file_logfile = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:logfile>",
    "Log file name",
    NULL,
    &cparser_node_snbi_root_debug_log_file_logfile_eol
};

cparser_node_t cparser_node_snbi_root_debug_log_file = {
    CPARSER_NODE_KEYWORD,
    0,
    "file",
    "Enable file logging",
    NULL,
    &cparser_node_snbi_root_debug_log_file_logfile
};

cparser_node_t cparser_node_snbi_root_debug_log_console_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_debug_log_console,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_debug_log_console = {
    CPARSER_NODE_KEYWORD,
    0,
    "console",
    "Enable console logging",
    &cparser_node_snbi_root_debug_log_file,
    &cparser_node_snbi_root_debug_log_console_eol
};

cparser_node_t cparser_node_snbi_root_debug_log = {
    CPARSER_NODE_KEYWORD,
    0,
    "log",
    "Modify message logging facilities",
    &cparser_node_snbi_root_debug_neighbor_discovery,
    &cparser_node_snbi_root_debug_log_console
};

cparser_node_t cparser_node_snbi_root_debug = {
    CPARSER_NODE_KEYWORD,
    0,
    "debug",
    "Debugging functions",
    NULL,
    &cparser_node_snbi_root_debug_log
};

cparser_node_t cparser_node_snbi_root_stop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_stop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_stop = {
    CPARSER_NODE_KEYWORD,
    0,
    "stop",
    "Disable SNBI protocol",
    &cparser_node_snbi_root_debug,
    &cparser_node_snbi_root_stop_eol
};

cparser_node_t cparser_node_snbi_root_start_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_start,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_start = {
    CPARSER_NODE_KEYWORD,
    0,
    "start",
    "Enable SNBI protocol",
    &cparser_node_snbi_root_stop,
    &cparser_node_snbi_root_start_eol
};

cparser_node_t cparser_node_snbi_root_interface_stop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_interface_stop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_interface_stop = {
    CPARSER_NODE_KEYWORD,
    0,
    "stop",
    "Stop neighbor discovery",
    NULL,
    &cparser_node_snbi_root_interface_stop_eol
};

cparser_node_t cparser_node_snbi_root_interface_start_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_interface_start,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_interface_start = {
    CPARSER_NODE_KEYWORD,
    0,
    "start",
    "Start neighbor discovery",
    &cparser_node_snbi_root_interface_stop,
    &cparser_node_snbi_root_interface_start_eol
};

cparser_node_t cparser_node_snbi_root_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    "SNBI interface",
    &cparser_node_snbi_root_start,
    &cparser_node_snbi_root_interface_start
};

cparser_node_t cparser_node_snbi_root_no_debug_bootstrap_type_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_no_debug_bootstrap_type_level,
    NULL,
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_level_sev = {
    NULL,
    "sev"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_level_moderate = {
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_level_sev,
    "moderate"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_level_info = {
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_level_moderate,
    "info"
 };

cparser_node_t cparser_node_snbi_root_no_debug_bootstrap_type_level = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_level_info,
    "Debugging level",
    NULL,
    &cparser_node_snbi_root_no_debug_bootstrap_type_level_eol
};

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_packets = {
    NULL,
    "packets"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_events = {
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_packets,
    "events"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_bootstrap_type_all = {
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_events,
    "all"
 };

cparser_node_t cparser_node_snbi_root_no_debug_bootstrap_type = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_no_debug_bootstrap_type_all,
    "Type of debugging",
    NULL,
    &cparser_node_snbi_root_no_debug_bootstrap_type_level
};

cparser_node_t cparser_node_snbi_root_no_debug_bootstrap = {
    CPARSER_NODE_KEYWORD,
    0,
    "bootstrap",
    "Bootstrap debug information",
    NULL,
    &cparser_node_snbi_root_no_debug_bootstrap_type
};

cparser_node_t cparser_node_snbi_root_no_debug_neighbor_discovery_type_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_no_debug_neighbor_discovery_type_level,
    NULL,
    NULL,
    NULL
};

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_sev = {
    NULL,
    "sev"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_moderate = {
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_sev,
    "moderate"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_info = {
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_moderate,
    "info"
 };

cparser_node_t cparser_node_snbi_root_no_debug_neighbor_discovery_type_level = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_level_info,
    "Debugging level",
    NULL,
    &cparser_node_snbi_root_no_debug_neighbor_discovery_type_level_eol
};

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_packets = {
    NULL,
    "packets"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_events = {
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_packets,
    "events"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_database = {
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_events,
    "database"
 };

cparser_list_node_t cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_all = {
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_database,
    "all"
 };

cparser_node_t cparser_node_snbi_root_no_debug_neighbor_discovery_type = {
    CPARSER_NODE_LIST,
    0,
    &cparser_list_node_snbi_root_no_debug_neighbor_discovery_type_all,
    "Type of debugging",
    NULL,
    &cparser_node_snbi_root_no_debug_neighbor_discovery_type_level
};

cparser_node_t cparser_node_snbi_root_no_debug_neighbor_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "neighbor-discovery",
    "Neighbor discovery debug information",
    &cparser_node_snbi_root_no_debug_bootstrap,
    &cparser_node_snbi_root_no_debug_neighbor_discovery_type
};

cparser_node_t cparser_node_snbi_root_no_debug = {
    CPARSER_NODE_KEYWORD,
    0,
    "debug",
    "Debugging functions",
    NULL,
    &cparser_node_snbi_root_no_debug_neighbor_discovery
};

cparser_node_t cparser_node_snbi_root_no_discovery_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_no_discovery,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_no_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "discovery",
    "SNBI neighbor discovery",
    &cparser_node_snbi_root_no_debug,
    &cparser_node_snbi_root_no_discovery_eol
};

cparser_node_t cparser_node_snbi_root_no = {
    CPARSER_NODE_KEYWORD,
    0,
    "no",
    "Negate a command",
    &cparser_node_snbi_root_interface,
    &cparser_node_snbi_root_no_discovery
};

cparser_node_t cparser_node_snbi_root_discovery_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_discovery,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "discovery",
    "Enable SNBI neighbor discovery",
    &cparser_node_snbi_root_no,
    &cparser_node_snbi_root_discovery_eol
};

cparser_node_t cparser_node_snbi_root_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_quit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_root_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    "Exit from SNBI mode",
    &cparser_node_snbi_root_discovery,
    &cparser_node_snbi_root_quit_eol
};

cparser_node_t cparser_node_snbi_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode snbi",
    NULL,
    &cparser_node_snbi_root_quit
};

cparser_node_t cparser_node_snbi_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi,
    NULL,
    NULL,
    &cparser_node_snbi_root
};

cparser_node_t cparser_node_snbi = {
    CPARSER_NODE_KEYWORD,
    0,
    "snbi",
    "SNBI mode",
    &cparser_node_test,
    &cparser_node_snbi_eol
};

cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    "Quit the simulator",
    &cparser_node_snbi,
    &cparser_node_quit_eol
};

cparser_node_t cparser_node_disable_privileged_mode_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_HIDDEN,
    cparser_glue_disable_privileged_mode,
    "Disable privileged mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_disable_privileged_mode = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_HIDDEN,
    "privileged-mode",
    "Privilege mode",
    NULL,
    &cparser_node_disable_privileged_mode_eol
};

cparser_node_t cparser_node_disable = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_HIDDEN,
    "disable",
    "Disable",
    &cparser_node_quit,
    &cparser_node_disable_privileged_mode
};

cparser_node_t cparser_node_enable_privileged_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_enable_privileged_mode,
    "Enable privileged mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_enable_privileged_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "privileged-mode",
    "Privilege mode requires a password",
    NULL,
    &cparser_node_enable_privileged_mode_eol
};

cparser_node_t cparser_node_enable = {
    CPARSER_NODE_KEYWORD,
    0,
    "enable",
    "Enable",
    &cparser_node_disable,
    &cparser_node_enable_privileged_mode
};

cparser_node_t cparser_node_show_snbi_intf_db_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_intf_db,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_intf_db = {
    CPARSER_NODE_KEYWORD,
    0,
    "intf-db",
    "Interface DB",
    NULL,
    &cparser_node_show_snbi_intf_db_eol
};

cparser_node_t cparser_node_show_snbi_neighbors_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_neighbors,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_neighbors = {
    CPARSER_NODE_KEYWORD,
    0,
    "neighbors",
    "SNBI Neighbors",
    &cparser_node_show_snbi_intf_db,
    &cparser_node_show_snbi_neighbors_eol
};

cparser_node_t cparser_node_show_snbi_device_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_device,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_device = {
    CPARSER_NODE_KEYWORD,
    0,
    "device",
    "Host device",
    &cparser_node_show_snbi_neighbors,
    &cparser_node_show_snbi_device_eol
};

cparser_node_t cparser_node_show_snbi = {
    CPARSER_NODE_KEYWORD,
    0,
    "snbi",
    "SNBI information",
    NULL,
    &cparser_node_show_snbi_device
};

cparser_node_t cparser_node_show_process_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_process,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_process = {
    CPARSER_NODE_KEYWORD,
    0,
    "process",
    "Active process statistics",
    &cparser_node_show_snbi,
    &cparser_node_show_process_eol
};

cparser_node_t cparser_node_show_ip_interfaces_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_ip_interfaces,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_ip_interfaces = {
    CPARSER_NODE_KEYWORD,
    0,
    "interfaces",
    "IP interface status and configuration",
    NULL,
    &cparser_node_show_ip_interfaces_eol
};

cparser_node_t cparser_node_show_ip = {
    CPARSER_NODE_KEYWORD,
    0,
    "ip",
    "IP information",
    &cparser_node_show_process,
    &cparser_node_show_ip_interfaces
};

cparser_node_t cparser_node_show_autonomic_interface_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_autonomic_interface,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_autonomic_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    "Autonomic Interfaces",
    NULL,
    &cparser_node_show_autonomic_interface_eol
};

cparser_node_t cparser_node_show_autonomic = {
    CPARSER_NODE_KEYWORD,
    0,
    "autonomic",
    "Autonomic Networking",
    &cparser_node_show_ip,
    &cparser_node_show_autonomic_interface
};

cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    "Show running system information",
    &cparser_node_enable,
    &cparser_node_show_autonomic
};

cparser_node_t cparser_node_clear_screen_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_clear_screen,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_clear_screen = {
    CPARSER_NODE_KEYWORD,
    0,
    "screen",
    "screen",
    NULL,
    &cparser_node_clear_screen_eol
};

cparser_node_t cparser_node_clear = {
    CPARSER_NODE_KEYWORD,
    0,
    "clear",
    "Clear functions",
    &cparser_node_show,
    &cparser_node_clear_screen
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_clear
};

