/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_show_autonomic_interface (cparser_t *parser)
{
    cparser_cmd_show_autonomic_interface(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_ip_interfaces (cparser_t *parser)
{
    cparser_cmd_show_ip_interfaces(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_process (cparser_t *parser)
{
    cparser_cmd_show_process(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_device (cparser_t *parser)
{
    cparser_cmd_show_snbi_device(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_neighbors (cparser_t *parser)
{
    cparser_cmd_show_snbi_neighbors(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_snbi_intf_db (cparser_t *parser)
{
    cparser_cmd_show_snbi_intf_db(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_discovery (cparser_t *parser)
{
    cparser_cmd_snbi_discovery(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_interface_start (cparser_t *parser)
{
    cparser_cmd_snbi_interface_start(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_interface_stop (cparser_t *parser)
{
    cparser_cmd_snbi_interface_stop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_start (cparser_t *parser)
{
    cparser_cmd_snbi_start(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_snbi_stop (cparser_t *parser)
{
    cparser_cmd_snbi_stop(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_no_snbi_discovery (cparser_t *parser)
{
    cparser_cmd_no_snbi_discovery(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_get_firstnode (cparser_t *parser)
{
    cparser_cmd_test_avl_get_firstnode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_init (cparser_t *parser)
{
    cparser_cmd_test_avl_init(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_insert_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_insert_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_remove_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_remove_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_search_value (cparser_t *parser)
{
    uint32_t value_val;
    uint32_t *value_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_uint(&parser->tokens[2], &value_val);
    assert(CPARSER_OK == rc);
    value_ptr = &value_val;
    cparser_cmd_test_avl_search_value(&parser->context,
        value_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_uninit (cparser_t *parser)
{
    cparser_cmd_test_avl_uninit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_test_avl_walk (cparser_t *parser)
{
    cparser_cmd_test_avl_walk(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_enable_privileged_mode (cparser_t *parser)
{
    cparser_cmd_enable_privileged_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_disable_privileged_mode (cparser_t *parser)
{
    cparser_cmd_disable_privileged_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_quit (cparser_t *parser)
{
    cparser_cmd_quit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_quit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_quit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_quit = {
    CPARSER_NODE_KEYWORD,
    0,
    "quit",
    NULL,
    NULL,
    &cparser_node_quit_eol
};

cparser_node_t cparser_node_disable_privileged_mode_eol = {
    CPARSER_NODE_END,
    CPARSER_NODE_FLAGS_HIDDEN,
    cparser_glue_disable_privileged_mode,
    "Disable privileged mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_disable_privileged_mode = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_HIDDEN,
    "privileged-mode",
    NULL,
    NULL,
    &cparser_node_disable_privileged_mode_eol
};

cparser_node_t cparser_node_disable = {
    CPARSER_NODE_KEYWORD,
    CPARSER_NODE_FLAGS_HIDDEN,
    "disable",
    NULL,
    &cparser_node_quit,
    &cparser_node_disable_privileged_mode
};

cparser_node_t cparser_node_enable_privileged_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_enable_privileged_mode,
    "Enable privileged mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_enable_privileged_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "privileged-mode",
    NULL,
    NULL,
    &cparser_node_enable_privileged_mode_eol
};

cparser_node_t cparser_node_enable = {
    CPARSER_NODE_KEYWORD,
    0,
    "enable",
    NULL,
    &cparser_node_disable,
    &cparser_node_enable_privileged_mode
};

cparser_node_t cparser_node_test_avl_walk_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_walk,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_walk = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-walk",
    NULL,
    NULL,
    &cparser_node_test_avl_walk_eol
};

cparser_node_t cparser_node_test_avl_uninit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_uninit,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_uninit = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-uninit",
    NULL,
    &cparser_node_test_avl_walk,
    &cparser_node_test_avl_uninit_eol
};

cparser_node_t cparser_node_test_avl_search_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_search_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_search_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    NULL,
    NULL,
    &cparser_node_test_avl_search_value_eol
};

cparser_node_t cparser_node_test_avl_search = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-search",
    NULL,
    &cparser_node_test_avl_uninit,
    &cparser_node_test_avl_search_value
};

cparser_node_t cparser_node_test_avl_remove_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_remove_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_remove_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    NULL,
    NULL,
    &cparser_node_test_avl_remove_value_eol
};

cparser_node_t cparser_node_test_avl_remove = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-remove",
    NULL,
    &cparser_node_test_avl_search,
    &cparser_node_test_avl_remove_value
};

cparser_node_t cparser_node_test_avl_insert_value_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_insert_value,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_insert_value = {
    CPARSER_NODE_UINT,
    0,
    "<UINT:value>",
    NULL,
    NULL,
    &cparser_node_test_avl_insert_value_eol
};

cparser_node_t cparser_node_test_avl_insert = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-insert",
    NULL,
    &cparser_node_test_avl_remove,
    &cparser_node_test_avl_insert_value
};

cparser_node_t cparser_node_test_avl_init_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_init,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_init = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-init",
    NULL,
    &cparser_node_test_avl_insert,
    &cparser_node_test_avl_init_eol
};

cparser_node_t cparser_node_test_avl_get_firstnode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_test_avl_get_firstnode,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_test_avl_get_firstnode = {
    CPARSER_NODE_KEYWORD,
    0,
    "avl-get-firstnode",
    NULL,
    &cparser_node_test_avl_init,
    &cparser_node_test_avl_get_firstnode_eol
};

cparser_node_t cparser_node_test = {
    CPARSER_NODE_KEYWORD,
    0,
    "test",
    NULL,
    &cparser_node_enable,
    &cparser_node_test_avl_get_firstnode
};

cparser_node_t cparser_node_no_snbi_discovery_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_no_snbi_discovery,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_no_snbi_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "discovery",
    NULL,
    NULL,
    &cparser_node_no_snbi_discovery_eol
};

cparser_node_t cparser_node_no_snbi = {
    CPARSER_NODE_KEYWORD,
    0,
    "snbi",
    NULL,
    NULL,
    &cparser_node_no_snbi_discovery
};

cparser_node_t cparser_node_no = {
    CPARSER_NODE_KEYWORD,
    0,
    "no",
    NULL,
    &cparser_node_test,
    &cparser_node_no_snbi
};

cparser_node_t cparser_node_snbi_stop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_stop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_stop = {
    CPARSER_NODE_KEYWORD,
    0,
    "stop",
    NULL,
    NULL,
    &cparser_node_snbi_stop_eol
};

cparser_node_t cparser_node_snbi_start_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_start,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_start = {
    CPARSER_NODE_KEYWORD,
    0,
    "start",
    NULL,
    &cparser_node_snbi_stop,
    &cparser_node_snbi_start_eol
};

cparser_node_t cparser_node_snbi_interface_stop_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_interface_stop,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_interface_stop = {
    CPARSER_NODE_KEYWORD,
    0,
    "stop",
    NULL,
    NULL,
    &cparser_node_snbi_interface_stop_eol
};

cparser_node_t cparser_node_snbi_interface_start_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_interface_start,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_interface_start = {
    CPARSER_NODE_KEYWORD,
    0,
    "start",
    NULL,
    &cparser_node_snbi_interface_stop,
    &cparser_node_snbi_interface_start_eol
};

cparser_node_t cparser_node_snbi_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    NULL,
    &cparser_node_snbi_start,
    &cparser_node_snbi_interface_start
};

cparser_node_t cparser_node_snbi_discovery_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_snbi_discovery,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_snbi_discovery = {
    CPARSER_NODE_KEYWORD,
    0,
    "discovery",
    NULL,
    &cparser_node_snbi_interface,
    &cparser_node_snbi_discovery_eol
};

cparser_node_t cparser_node_snbi = {
    CPARSER_NODE_KEYWORD,
    0,
    "snbi",
    NULL,
    &cparser_node_no,
    &cparser_node_snbi_discovery
};

cparser_node_t cparser_node_show_snbi_intf_db_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_intf_db,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_intf_db = {
    CPARSER_NODE_KEYWORD,
    0,
    "intf-db",
    NULL,
    NULL,
    &cparser_node_show_snbi_intf_db_eol
};

cparser_node_t cparser_node_show_snbi_neighbors_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_neighbors,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_neighbors = {
    CPARSER_NODE_KEYWORD,
    0,
    "neighbors",
    NULL,
    &cparser_node_show_snbi_intf_db,
    &cparser_node_show_snbi_neighbors_eol
};

cparser_node_t cparser_node_show_snbi_device_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_snbi_device,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_snbi_device = {
    CPARSER_NODE_KEYWORD,
    0,
    "device",
    NULL,
    &cparser_node_show_snbi_neighbors,
    &cparser_node_show_snbi_device_eol
};

cparser_node_t cparser_node_show_snbi = {
    CPARSER_NODE_KEYWORD,
    0,
    "snbi",
    NULL,
    NULL,
    &cparser_node_show_snbi_device
};

cparser_node_t cparser_node_show_process_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_process,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_process = {
    CPARSER_NODE_KEYWORD,
    0,
    "process",
    NULL,
    &cparser_node_show_snbi,
    &cparser_node_show_process_eol
};

cparser_node_t cparser_node_show_ip_interfaces_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_ip_interfaces,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_ip_interfaces = {
    CPARSER_NODE_KEYWORD,
    0,
    "interfaces",
    NULL,
    NULL,
    &cparser_node_show_ip_interfaces_eol
};

cparser_node_t cparser_node_show_ip = {
    CPARSER_NODE_KEYWORD,
    0,
    "ip",
    NULL,
    &cparser_node_show_process,
    &cparser_node_show_ip_interfaces
};

cparser_node_t cparser_node_show_autonomic_interface_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_autonomic_interface,
    NULL,
    NULL,
    NULL
};

cparser_node_t cparser_node_show_autonomic_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    NULL,
    NULL,
    &cparser_node_show_autonomic_interface_eol
};

cparser_node_t cparser_node_show_autonomic = {
    CPARSER_NODE_KEYWORD,
    0,
    "autonomic",
    NULL,
    &cparser_node_show_ip,
    &cparser_node_show_autonomic_interface
};

cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    NULL,
    &cparser_node_snbi,
    &cparser_node_show_autonomic
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_show
};

